### ISSUE TITLE
Code Coverage Report is Confusing

### ISSUE THREAD

**Issue by amonshiz** [DataDog/dd-sdk-swift-testing#136]
We are attempting to use the DataDog [code coverage](https://docs.datadoghq.com/tests/code_coverage/?tab=javascripttypescript) tooling to monitor and improve testing. However, when we enable this feature we find that the results reported differ significantly from Xcode and appear to be difficult to understand.

For example, when we set `DD_CIVISIBILITY_CODE_COVERAGE_ENABLED=1` for a CI run we see the following information for our tests:
- DataDog reports that `test CoreMacrosTests` has 16.7% coverage
  ![CleanShot 2024-09-12 at 12 59 00@2x](https://github.com/user-attachments/assets/780b200a-8be7-4bb1-94a3-40a87473e107)

- Xcode reports 0% coverage
  ![CleanShot 2024-09-12 at 13 00 48@2x](https://github.com/user-attachments/assets/65eca39f-5c86-4efb-86ad-a6c97e617a91)

Both of these values are confusing:
- There is no way to know which code DataDog considers to have been covered.
- The tests in question definitely exercise the macros, but Xcode cannot seemingly determine that (this is an issue with Xcode and its SPM macro integration, but is still confusing).

I believe that the biggest difference is that Xcode reports based on the files "touched" by the tests executed and DataDog is maybe reporting based on the percent of total lines in the repo that were touched? Both of these metrics are less than perfect:
- Xcode's will ignore any file that is untouched and so not really give any insight into changes at the global level. But this does provide information regarding changes at the file and even method level.
- DataDog's seems to include all lines of code in the repo? This is great to get a global view of coverage over time but is not particularly useful when trying to understand how much of any given file is covered or if a new test had any impact on a specific file or method. Additionally, DataDog's web visualization is only by the test session and provides no kind of visual indication of which lines are covered by tests.

What is the guidance on how to actually use the DataDog Swift Testing SDK's code coverage integration? Is there a way for us to use it to understand the code coverage at a source file level? Is there something we are missing to view the lines covered in the DataDog UI?

**Comment by ypopovych** [comment]
Hello.

There are 2 types of code coverage in the DD library - session code coverage and per-test code coverage.

Per-test code coverage is used for ITR. It gathers lines and files which were executed when the test run.

Percents are reported by the session code coverage. It uses all source code used for the current test session and lines executed in this test session. Seems as Xcode filters it on per-target basis. That's why percents can differ. In case of DD we will have percents for the full session (and all targets) together.
