### ISSUE TITLE
[Question] Cocoapods support

### ISSUE THREAD

**Issue by dcacenabes** [DataDog/dd-sdk-swift-testing#39]
### Cocoapods support

Is distributing this framework as a pod in the roadmap? Although SPM is great, there are still some limitations can prevent a team from adopting it. (e.g. impossibility to specify a package for just one build configuration)
I know you also provide direct download for the  xcframework (I assume it's built with ABI stability), but I would like to use this with a dependency management tool.

**Comment by nachoBonafonte** [comment]
Hi David,

Yes, Cocoapods support is in the roadmap, although it was not very high in the priority list. Now that you ask for it we can increase the priority.

About the xcframework, it is built with ABI stability, so should work with different versions of swift. We are also using it for the SPM versions that support binary distribution (to avoid downloading and building the whole package and dependencies each time).

**Comment by dcacenabes** [comment]
Thanks for your reply. For the time being we are using the node version and uploading the junit results from the CI. Looking forward to start using it with Cocoapods and being able to gather data directly from Xcode.

**Comment by nachoBonafonte** [comment]
Results directly from Xcode are much richer than what junit results can provide. Specifically for iOS, apart from information about the device or simulator running the test, it allows for full visualisation of integration tests, symbolication of test crashes when running on simulator, support for `measure` call in benchmark tests, and many other features to help in identifying the root cause of test failure/flakiness. 

If you decide to give it a try before we support Cocoapods, please provide any feedback or issues (we are currently in beta) you can find  and we will do our best to improve your experience.

**Comment by dcacenabes** [comment]
🤔 Since your XCFramework is ABI stable, I might create a private repo, dump a podspec there and start consuming the binary from there...
Having the symbolication of test crashes might be super useful. Although not always, we do get some crashes in the test suite.

Extra question:
Is it possible from the agent to get some URL to the test report in Datadog? Maybe from an env var or somewhere? I am thinking this could be useful to attach the URL in the PR or in the CI to the job to make it easier for the dev to get there 🤔

**Comment by nachoBonafonte** [comment]
> Is it possible from the agent to get some URL to the test report in Datadog? Maybe from an env var or somewhere? I am thinking this could be useful to attach the URL in the PR or in the CI to the job to make it easier for the dev to get there 🤔

Not at the moment, the URL's for the different views are still not final, and might break at any time. But we are working on a solution for it.

> (If I have more unrelated questions, would you like me to open a new issue for each? Or is it fine if I address all of those here?)

I would prefer having a new issue for each question, that way and I can order the issues and related task on the project easier, and also can help other users to find the information better.

**Comment by nachoBonafonte** [comment]
Hi, version 0.9.3 is already available in the public repository of Cocoapods with the name `DatadogSDKTesting`, it distributes `DatadogSDKTesting.xcframework` as a `vendored_framework.

**Comment by dcacenabes** [comment]
> Hi, version 0.9.3 is already available in the public repository of Cocoapods with the name `DatadogSDKTesting`, it distributes `DatadogSDKTesting.xcframework` as a `vendored_framework`.

Amazing! Thanks for such a quick response. Will test this tomorrow already.

**Comment by dcacenabes** [comment]
I was testing in one of our projects and I realised that the pod requires iOS 12 as per podspec:
https://github.com/CocoaPods/Specs/blob/ef62595ca58dc885a4bb3da9ed00f04861cb4970/Specs/b/3/6/DatadogSDKTesting/0.9.3/DatadogSDKTesting.podspec.json

But when I was testing manually the integration (imported my own version) it worked with a project running iOS 11. Is there anything I missed on my tests?

**Comment by nachoBonafonte** [comment]
The framework was using iOS 12 as deployment target in Xcode, so thats what was set in the podspec. But after your feedback I have checked that it would also work with iOS 11, so I am changing the deployment target to iOS 11 and will also change the podspec accordingly.

I was planning to release a 0.9.4 version today with the configuration also supporting using the Info.plist file ( as talked in #40 ), but I will also add this iOS version change to the framework and to the podspec

**Comment by dcacenabes** [comment]
Thanks a lot.
I have already added the pod to one of our apps that has deployment target >= 12.0 . So far all good 👍

**Comment by nachoBonafonte** [comment]
I have already released version 0.9.4 and pushed the podspec for it. It adds support for iOS version 11.0
