### ISSUE TITLE
[Question] Manual launch support

### ISSUE THREAD

**Issue by dcacenabes** [DataDog/dd-sdk-swift-testing#40]
### Support loading the tool manually

Loading the tool automatically is really nice and works for most use cases. It also helps keeping things simple. We have a use case, though, in which manual config would be really helpful: running tests in Amazon Device Farm. When running UI Tests in ADF, we do not trigger the run from Xcode. Instead, we upload both IPA files for the runner and for the target app to a bucket and ADF will orchestrate the test run. It'd be great for such use case if we could manually load the tool with a custom config directly from the code.

What are your thoughts?

**Comment by nachoBonafonte** [comment]
I had really not thought about this use case, and I am also not familiar with Amazon Device Farm, so I should investigate more about it before giving a clear answer; but, doesn’t ADF support setting environment variables for the running apps? Would reading the configuration from e.g. the Info.plist file be an acceptable solution?

**Comment by dcacenabes** [comment]
ADF supports setting environment variables but it comes at a price. We would lose automatic test video generation (they would provide just one big video with all test runs) and we would also lose some of the logs they provide. They partially overlap with what DD provides, but being able to look at the logs in ADF is still useful to us.

The plist approach can totally work for us. We can rely on [Fastlane's update_plist](https://docs.fastlane.tools/actions/update_plist/) to add the token there from the CI before triggering the build.

**Comment by dcacenabes** [comment]
Please do not take this as me trying to put pressure. I'd like to know if there's any expected ETA for this to make it to the product (if it ever makes it). Are we talking about weeks? months? >year? It'd help us plan our strategy. I totally understand if the answer is no ETA at all.
Thanks in advance! 🙏

**Comment by nachoBonafonte** [comment]
I am currently working on it, the solution I am currently coding is by setting the same values in the plist file of the test bundle (not on the app bundle), would that work for you?

**Comment by dcacenabes** [comment]
> I am currently working on it, the solution I am currently coding is by setting the same values that are set in the environment but in the plist file of the test bundle (not on the app bundle), would that work for you?

Yes, we are already injecting some values in the UI Test bundle like that. That's great!

**Comment by nachoBonafonte** [comment]
Version [0.9.4](https://github.com/DataDog/dd-sdk-swift-testing/releases/tag/0.9.4) adds support for configuration using the `Info.plist` file of the test bundle. As said previously it uses the same name and format of the environment variables but readed from the plist file. If both environment variables and `Info.plist` file includes the same setting, environment values always take precedence.
