### ISSUE TITLE
[Question] Xcode 13 automatic test repetition compatibility

### ISSUE THREAD

**Issue by dcacenabes** [DataDog/dd-sdk-swift-testing#41]
### Automatic test repetition support

Last WWDC Apple [presented automatic test repetition](https://developer.apple.com/videos/play/wwdc2021/10296/)
I was wondering if this framework will be compatible with this, and will flag a test that passed after being automatically repeated as flaky.

Thanks!

**Comment by nachoBonafonte** [comment]
From my current tests, yes, the framework is already compatible with automatic test repetition and can work with XCode 13 beta. Said that I must also say it has still not been deeply tested with it.

Currently any test is marked as flaky when both passes and fails for the same commit and the same configuration (e.g. a test that passes in iOS 13 and fails in iOS 14, or that fails in iPhone and passes in iPad for the same commit is not considered flaky but a failure)

About the flakiness of the tests with automated test repetition, it will be marked as flaky if it has proper git information. A test is marked as flaky at the backend not at the tracer level. How the test is repeated (being it the XCTest test plan, or a retry at the CI level) makes no difference for the flakiness of it.

**Comment by dcacenabes** [comment]
Great to hear this! Looking forward to testing it. Thanks.
