### ISSUE TITLE
Data Dog sdk was compiled without bitcode and it’s preventing from generating a release build

### ISSUE THREAD

**Issue by luisasalas** [DataDog/dd-sdk-swift-testing#45]
It's complaining about the library not supporting bitcode which we support in our app. 

This is the error we get when trying to create a release build.

`ld: '/Users/*****/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/DatadogSDKTesting.framework/DatadogSDKTesting' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/****/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/DatadogSDKTesting.framework/DatadogSDKTesting' for architecture arm64`

**Comment by nachoBonafonte** [comment]
Hi,
Yes that is a known limitation, this framework depends on XCTest framework, which doesn't contain bitcode itself, so it is not possible to build it with bitcode enabled. 

This is a framework for instrumenting of your tests, usually tests are run on Debug builds of your app to keep all debug info and disabling bitcode in Debug mode should not be an issue. But there are some situations when running on a physical device and in Release is needed (performance benchmarks mainly), for those situations the only possible solution is disabling Bitcode in the target app where tests are going to run. 

You should not release an app to users with this framework linked in(probably will not pass AppStore checks), so you already need to have two different release targets, one for distribution and one for testing, so you should disable bitcode for the target used for testing and enable for the distributable target.
