### ISSUE TITLE
Manual reporting of test results no longer working

### ISSUE THREAD

**Issue by nighthawk** [DataDog/dd-sdk-swift-testing#63]
The manual reporting of test results (see #47) has stopped working on our system. 

I updated to the latest version and switched to using `DD_API_KEY`, and updated how we trigger it to something like this:

```bash
DD_API_KEY={apiKey} DD_TEST_RUNNER=1 DD_SERVICE={ourService} SRCROOT=. DD_DISABLE_CRASH_HANDLER=1 DD_ENV=ci swift run {executableTarget} {ourParameters}
```

The results were previously reported nicely on https://app.datadoghq.com/ci/test-services, but they don't show up anymore.

---

I tried set `DD_DEBUG_TRACE=1` and I this output from Datadog at the start of the run:

```
[DatadogSDKTesting]Library loaded and active. Instrumenting tests.
[Debug][DatadogSDKTesting]Loaded images: {long list}
```

And this at the end:

```
[Debug][DatadogSDKTesting]DDCFMessageID.forceFlush finished
```

But nothing in between.

Any help or advice would be much appreciated!

**Comment by nighthawk** [comment]
Found the error. It was on my end. Sorry about that :)

**Comment by nachoBonafonte** [comment]
Glad you found it. 

Having to change to DD_API_KEY was not a deliberate breaking change, it was forced by some of the new features we are going to release soon that need a higher validation scheme, so I am sure it will pay off later.
